version: '2'
services:
  ghost:
    container_name: ghost
    image: ghost:1.12.1
    volumes:
      - ./ghost-db:/var/lib/ghost/content/
    expose:
      - "2368"
    environment:
      - url=https://steven.news
  nginx:
    image: nginx:1.13.5
    links:
      - ghost
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      VIRTUAL_HOST: steven.news,www.steven.news,cdn.steven.news
      LETSENCRYPT_HOST: steven.news,www.steven.news,cdn.steven.news
      LETSENCRYPT_EMAIL: stevenc81@gmail.com
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    ports:
      - "443:443"
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

