version: '2'
services:
  ghost:
    image: ghost:1.20.0
    volumes:
      - ./ghost-db/:/var/lib/ghost/content/
    expose:
      - "2368"
    environment:
      url: https://steven.news
      VIRTUAL_HOST: steven.news,www.steven.news
      LETSENCRYPT_HOST: steven.news,www.steven.news
      LETSENCRYPT_EMAIL: stevenc81@gmail.com
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    links:
      - ghost
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
